### ISSUE TITLE
Create Release

### ISSUE THREAD

**Issue by clandaith** [BSData/gates-of-antares#58] opened 2016-05-30 20:56 UTC
Does everyone have their changes in the master branch?  If so, I'll create a release for the files.

**Comment by amis92** [comment] 2016-06-08 06:35
@clandaith (and any other people who might consider releasing in future). According to https://github.com/BSData/gates-of-antares/tags there is quite none uniformity to release tags/versions. You've released v3.1, whereas there were lately both versions 5.xx and 1.5x and similar.

Please consider making effort to make those tags uniform. It'd be best to follow the actual guidelines as written on this wiki page: https://github.com/BSData/bsdata/wiki/Developer-Guide#how-to-release (see **Our convention** bullet point).

Cheers and thanks for the effort!

**Comment by glasvandrare** [comment] 2016-06-08 10:46
Good point, @amis92 .
Everyone, could we try to keep a unified release syntax from now on? 
And also increment the file versions when updating them? 

My suggestion is that we create the next release as 1.6.0, an then move up to 2.0.0 when we've gotten the Xilos content added.

**Comment by clandaith** [comment] 2016-06-08 13:41
Works for me.  I looked at the previous release and saw that it was v3.
That's why I did 3.1.  @glasvandrare, I agree with that numbering pattern.

++++++++++++++++++
Troy Davidson, KF7MTE

**Comment by glasvandrare** [comment] 2016-06-13 20:37
Great work, Troy. Come this weekend I should have a few hours to put in with any issues, or get started on BfX (got the book today!).
Should we make a release with the Ghar and Concorde fixes you did today?

**Comment by clandaith** [comment] 2016-06-13 21:36
I would say yes.  We don't have to version to 2.0 yet, but start pumping
out releases more frequently.

++++++++++++++++++
Troy Davidson, KF7MTE

**Comment by glasvandrare** [comment] 2016-06-14 19:53
I'll make a release based on what we have merged currently, then. 
@amis92 : Is there any good way of editing previous tags to conform to standards?

**Comment by amis92** [comment] 2016-06-14 20:44
Well you can edit tags, but you have to be careful _not_ to update them onto the latest commit. If you know what you're doing, you can, otherwise it's better to just leave it and forget about it. **Most important:** don't delete them tags! AppSpot app runs currently against _number_ of releases, and only updates itself if the count increased since last check.

**Comment by glasvandrare** [comment] 2016-06-15 19:23
Thanks for the reply. It seems that the release I did last night has not been picked up by AppSpot, any idea why?

**Comment by clandaith** [comment] 2016-06-15 20:39
It can take a few days for it to appear.

**Comment by amis92** [comment] 2016-06-15 20:44
@glasvandrare if you're talking about https://github.com/BSData/gates-of-antares/releases/tag/V1.5.23 it's not actually a Release, you've only tagged the commit.

To create Release, please click `Draft a new release` in upper right here: https://github.com/BSData/gates-of-antares/releases and then `Publish release`, not `Save draft`.

If you're talking about something else, I can't see it (the link above lists all releases, last was made by **Vescarea**, V1.6.0)

---

And it shouldn't take more than few hours. When it's more than 12 hours you can start wondering where's the issue.

**Comment by glasvandrare** [comment] 2016-06-15 20:50
It's actually 1.6.0 I'm talking about, it is not listed in the app spot contents.

**Comment by amis92** [comment] 2016-06-15 20:55
Okay, I've actually gone to the [AppSpot](http://battlescribedata.appspot.com/#/repo/gates-of-antares). It definitely seems like it's missing the latest release. I have no access to logs, so you'll have to try contacting @Jonskichov. Other than that, you can try also these:
- check all catalogues are working (ie no errors)
- check nothing is zipped
- scratch your forehead and wait for @Jonskichov (or engage him on Twitter).

**Comment by glasvandrare** [comment] 2016-06-15 21:25
OK, thanks. We're absolutely sure that the step down in version numbers couldn't affect the delivery?

I'll double check for errors, but I've not seen any so far.

**Comment by amis92** [comment] 2016-06-15 21:45
100%. I've actually gone so far as to check source code: https://github.com/BSData/bsdata/blob/master/src/java/org/bsdata/dao/GitHubDao.java#L282

It checks if the latest release has newer release date than the one currently hosted.

**Comment by glasvandrare** [comment] 2016-06-16 11:37
The only errors I find is the usual in RosterEditor about minimum Roster requirements... 

I'll see if I can reach out to @Jonskichov on Twitter.

**Comment by glasvandrare** [comment] 2016-07-25 13:35
So, it seems that my release today at least was picked up by Appspot, even though the last one wasn't. 
Do we have any bugs in the Appspot setup regarding release detection? 
And why is the actual file not currently reachable, even though it is published?

**Comment by glasvandrare** [comment] 2016-07-26 06:45
Never mind, removing the zipped files sorted it out.

**Comment by amis92** [comment] 2016-07-26 21:53
Glad to hear the issue is resolved. :)

**Closed as completed by amis92** 2016-07-26 21:53 UTC
