### ISSUE TITLE
[Anon] Bug report: Ghar.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/gates-of-antares#169] opened 2019-04-24 09:35 UTC
**File:** Ghar.catz

**BattleScribe version:** 2.01.22

**Platform:** Android

**Dropbox:** No

**Description:** No entry for Tactical Command Squad

Additional assault squad troopers are overcosted at 60 points each, should be 57 each

Additional battle squad troopers  are also overcosted at 60 points each, should be 57 each

Outcast command squad should be 38 points, not 40

Additional outcast command squad outcasts are under costed at 4 points each, should be 6 points each

Outcast squad should be 42 points, not 43

Additional outcasts should be 6 points each, not 5

Weapon team should be 23 points not 24

No option for Vac armour

Outcast weapon team should be 23 points not 24

Outcast leader for weapon team should be 11 points not 9

Plasma dumps for command crawler should be 5 points not free

Additional troopers for bomber squads should be 57 each

Attack scutters should be 91 points not 88

No entry for transport dropper

Special rule “Sharded Infantry Unit” should be removed from Tectorists

No entry for Munition Scutter

Bombardment crawler should be 258 points not 256

**Comment by TimCoraxAudio** [comment] 2019-04-24 10:20
Duplicate of #159 

Will have to go through and create a final ghar update list that needs to happen

**Comment by TimCoraxAudio** [comment] 2019-04-24 10:33
There are 2 related issues with this, all replies should be sent to issue #171 in future

**Closed as completed** 2019-04-29 07:44 UTC
Labels: duplicate
